name: Run febug tests

on:
  pull_request:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:stable
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install pyvista

      - name: Run unit tests
        run: python3 -m pytest test/
