name: febug unit tests

on:
  schedule:
    - cron: 0 0 * * 0 # weekly at 00:00 on Sunday
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:nightly
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: python3 -m pip install --break-system-packages pyvista pytest

      - name: Install python package
        run: python3 -m pip install --check-build-dependencies .
 
      - name: Run unit tests
        run: python3 -m pytest test/
